kind: Deployment
apiVersion: apps/v1
metadata:
  name: php-deployment
  namespace: hvac
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: shojibflamon/docker-hvac-php:latest
        ports:
        - containerPort: 9000
