kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: hvac
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: shojibflamon/docker-hvac-nginx:latest
#        image: nginx:latest
        ports:
        - containerPort: 80
